### PR TITLE
DeepFreeze Compatible

### PR DESCRIPTION
**Pull request by JPLRepo**
Compatible with DeepFreeze mod

### CODE REVIEW

**Comment by JPLRepo** [comment]
This small change will make TAC LS compatible with DeepFreeze mod.
Requires DFInterface.DLL file (can be downloaded from DeepFreeze GITHUB repository to be referenced in build). Not included in this pull request.

**Comment by austinjames314** [comment]
I hope this is merged. Seems like the perfect way for these mods to complement one another.

**Comment by JPLRepo** [comment]
Doesn't look like taraniselsu is going to release it soon.   
taraniselsu: you need to download and reference this API DLL   
https://github.com/JPLRepo/DeepFreeze/blob/master/DFInterface.zip
I have been using my own version for months now and it works fine.

**Comment by amedee** [comment]
@JPLRepo Your forked repo is now several commits behind and one commit ahead of this repo. Which means that if I use your modified `TacLifeSupport.dll`, I won't have the new features that were added to TACLS. As long as @taraniselsu doesn't merge your pull request, you will have to provide an up-to-date `TacLifeSupport.dll` I'm afraid.

**Comment by JPLRepo** [comment]
I am currently away on holidays and not in a position (do not have pc) to do anything until the New Year. It would be better if this pull request was just merged in. It does require downloading adding a reference and including my API dll in TACLS. I don't know if that is the issue or Time or something else?

**Comment by taraniselsu** [comment]
What is holding me back from incorporating this:
1) Time. I have not had much time to work on anything KSP :(
2) I have to include your DLL in my releases, and the game will crash if it is not there. There are ways to make it look for and use another class only if the DLL is loaded without building in a hard dependency (see #75 or Blizzy's toolbar).
3) I have a better solution that I have partially implemented in the new version that I have been trying to work on. But see (1) above.

**Comment by taraniselsu** [comment]
Please note that this is _**completely untested**_, I just merged JPLRepo's change and recompiled. I take no responsibility _whatsoever_.

[Download from Dropbox](https://www.dropbox.com/s/60yw6ffeeuiu137/TacLifeSupport-DeepFreeze-UNTESTED_0.11.2.6.zip?dl=0)

**Comment by JPLRepo** [comment]
Sure I understand. I wrote the API DLL thinking you were not allowed to use reflection in mods (thought it was a KSP mod - Squad rule) but subsequently realised you can use reflection. If you like to wait, I will re-write my API as a reflection class that you can just add to your project without the hard DLL dependency. I am away on holidays now. But will be back just before New Year anvil have nearly two weeks leave then. So I will re-write it and let you know when it's done.

**Comment by JPLRepo** [comment]
I have completed writing and testing a wrapper class API for DeepFreeze and released it. this will allow you to recognize and support DeepFreeze integration without needing a hard DLL reference. Let me know if you have time, or I can go through and do an update and push you the necessary changes.
[Link to wiki description.](https://github.com/JPLRepo/DeepFreeze/wiki/DeepFreeze-API---Wrapper-Class)
 Thanks.

**Comment by JPLRepo** [comment]
I am closing this pull request and will create a new one with new code change using new DeepFreeze wrapper class API.

**Pull request closed without merging**
